# Generated by Django 5.1.4 on 2026-05-04 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='Заповнюється автоматично з заголовку', max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, help_text='Відображається у картці новини', max_length=400, verbose_name='Короткий опис')),
                ('content', models.TextField(verbose_name='Повний текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='Обкладинка')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опублікована')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-published_at'],
            },
        ),
    ]
