# Generated by Django 5.1.4 on 2026-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Повний текст'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_uk',
            field=models.TextField(null=True, verbose_name='Повний текст'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_en',
            field=models.TextField(blank=True, help_text='Відображається у картці новини', max_length=400, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_uk',
            field=models.TextField(blank=True, help_text='Відображається у картці новини', max_length=400, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seo_description_uk',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Заповнюється автоматично при імпорті з RSS', max_length=500, verbose_name='Джерело (URL оригіналу)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
