# Generated by Django 5.1.4 on 2026-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_seed_market_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('market', 'Новини ринку'), ('company', 'Новини компанії')], default='market', max_length=20, verbose_name='Категорія'),
        ),
    ]
