# Generated by Django 5.1.4 on 2026-05-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='CSS клас або ідентифікатор SVG', max_length=60, verbose_name='Іконка')),
                ('title', models.CharField(max_length=120, verbose_name='Перевага')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CooperationBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('cta_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для CTA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Банер Співпраця',
                'verbose_name_plural': 'Банери Співпраця',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('cta_text', models.CharField(blank=True, max_length=60, verbose_name='Текст кнопки CTA')),
                ('cta_url', models.CharField(blank=True, max_length=255, verbose_name='URL кнопки CTA')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фонове зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Секція Hero',
                'verbose_name_plural': 'Секції Hero',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='Наприклад: icon-cooperation або handshake', max_length=60, verbose_name='Іконка (CSS клас або SVG назва)')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Led leader', max_length=120, verbose_name='Назва сайту')),
                ('tagline', models.CharField(default='Digital Equipment', max_length=255, verbose_name='Слоган')),
                ('description', models.TextField(blank=True, default='', verbose_name='Короткий опис компанії')),
                ('founded_year', models.PositiveSmallIntegerField(default=2006, verbose_name='Рік заснування')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='OG Image')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Favicon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
            },
        ),
    ]
