# Generated by Django 5.1.4 on 2026-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Перевага'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='Перевага'),
        ),
        migrations.AddField(
            model_name='cooperationbanner',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='cooperationbanner',
            name='body_uk',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='cooperationbanner',
            name='heading_en',
            field=models.CharField(max_length=160, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='cooperationbanner',
            name='heading_uk',
            field=models.CharField(max_length=160, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='body_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Текст кнопки CTA'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_uk',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Текст кнопки CTA'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Короткий опис компанії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Короткий опис компанії'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description_uk',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='Led leader', max_length=120, null=True, verbose_name='Назва сайту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_uk',
            field=models.CharField(default='Led leader', max_length=120, null=True, verbose_name='Назва сайту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(default='Digital Equipment', max_length=255, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_uk',
            field=models.CharField(default='Digital Equipment', max_length=255, null=True, verbose_name='Слоган'),
        ),
    ]
