# Generated by Django 5.1.4 on 2026-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_advantage_title_en_advantage_title_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_advertising',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email реклами (reklama@)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_hr',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email HR (hr-manager@)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_manager_1',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email менеджера 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_manager_2',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email менеджера 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_partner',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email партнерства (partner@)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_sales',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email відділу продажів (sales@)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Основний email (info@)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон (багатоканальний)'),
        ),
    ]
