# Generated by Django 5.2.15 on 2026-07-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_site_settings_contact_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_code',
            field=models.TextField(blank=True, default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d20328.566181121325!2d30.5007107!3d50.4397824!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4ce88e35e395f%3A0xc63774cf5da5a434!2z0KHQvtGE0LjQudGB0LrQuNC5INGB0L7QsdC-0YA!5e0!3m2!1sru!2sua!4v1783689698284!5m2!1sru!2sua" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe>', help_text='Вставте повний код &lt;iframe&gt;...&lt;/iframe&gt;, отриманий у Google Maps через «Поділитися → Вставити карту». Якщо поле порожнє — показується карта Європи за замовчуванням.', verbose_name='Код карти (iframe з Google Maps або OpenStreetMap)'),
        ),
    ]
