# Generated by Django 5.1.4 on 2026-07-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_site_settings_map_embed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва компанії')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Назва компанії')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Назва компанії')),
                ('logo', models.ImageField(blank=True, help_text='Рекомендований розмір: 160×56 px (співвідношення сторін ≈ 2.85:1). Формат SVG або PNG з прозорим фоном. Якщо логотип не завантажено — буде показано стандартну іконку.', null=True, upload_to='carriers/', verbose_name='Логотип')),
                ('description', models.TextField(help_text='Короткий опис служби доставки та орієнтовні терміни доставки.', verbose_name='Опис')),
                ('description_uk', models.TextField(help_text='Короткий опис служби доставки та орієнтовні терміни доставки.', null=True, verbose_name='Опис')),
                ('description_en', models.TextField(help_text='Короткий опис служби доставки та орієнтовні терміни доставки.', null=True, verbose_name='Опис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Транспортна компанія',
                'verbose_name_plural': 'Транспортні компанії',
                'ordering': ['order'],
            },
        ),
    ]
