# Generated by Django 5.2.15 on 2026-07-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='partner_contract_file',
            field=models.FileField(blank=True, help_text='Файл, який завантажується на сторінці «Стати партнером» (.doc, .docx, .pdf).', null=True, upload_to='docs/', verbose_name='Договір купівлі-продажу (файл)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warranty_act_file',
            field=models.FileField(blank=True, help_text='Файл, який завантажується на сторінці «Сервіс і гарантія» (.xlsx, .pdf, .doc).', null=True, upload_to='docs/', verbose_name='Акт приймання на гарантійний ремонт (файл)'),
        ),
    ]
