# Generated by Django 5.1.4 on 2026-07-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_partner_contract_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Питання')),
                ('question_uk', models.CharField(max_length=255, null=True, verbose_name='Питання')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('answer_uk', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_en', models.TextField(null=True, verbose_name='Відповідь')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Питання F.A.Q.',
                'verbose_name_plural': 'F.A.Q. — Часті питання',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InternalExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=20, verbose_name='Внутрішній номер')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Внутрішній номер телефону',
                'verbose_name_plural': 'Внутрішні номери телефону',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about_intro', 'Про компанію — основний текст'), ('cooperation_intro', 'Співпраця — вступний текст'), ('cooperation_note', 'Співпраця — примітка перед контактами'), ('partners_intro', 'Партнери — вступний текст'), ('delivery_intro', 'Доставка — вступний текст'), ('delivery_conditions', 'Доставка — умови співпраці'), ('delivery_discounts', 'Доставка — умови знижок'), ('delivery_order_steps', 'Замовлення та оплата — кроки замовлення'), ('delivery_order_payment', 'Замовлення та оплата — способи оплати'), ('delivery_transport_intro', 'Транспортні компанії — вступний текст'), ('delivery_transport_note', 'Транспортні компанії — примітка'), ('partners_program_intro', 'Партнерська програма — вступ і переваги'), ('partners_program_outro', 'Партнерська програма — заключний текст'), ('partners_become_contract', 'Стати партнером — вступ перед посиланням на договір'), ('partners_become_contract_followup', 'Стати партнером — текст після посилання на договір'), ('partners_become_careers', 'Стати партнером — блок про вакансії'), ('partners_service_intro', 'Сервіс і гарантія — вступний текст'), ('partners_service_terms', 'Сервіс і гарантія — умови гарантійного ремонту'), ('partners_service_kit', 'Сервіс і гарантія — комплект поставки')], max_length=50, unique=True, verbose_name='Сторінка/блок')),
                ('body', models.TextField(blank=True, verbose_name='Текст (HTML)')),
                ('body_uk', models.TextField(blank=True, null=True, verbose_name='Текст (HTML)')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Текст (HTML)')),
            ],
            options={
                'verbose_name': 'Текст сторінки',
                'verbose_name_plural': 'Тексти сторінок',
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='PartnerRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва області/регіону')),
                ('name_uk', models.CharField(max_length=120, null=True, verbose_name='Назва області/регіону')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='Назва області/регіону')),
                ('cities', models.TextField(blank=True, help_text='Кожне місто — з нового рядка.', verbose_name='Міста')),
                ('cities_uk', models.TextField(blank=True, help_text='Кожне місто — з нового рядка.', null=True, verbose_name='Міста')),
                ('cities_en', models.TextField(blank=True, help_text='Кожне місто — з нового рядка.', null=True, verbose_name='Міста')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Регіон партнерів',
                'verbose_name_plural': 'Регіони партнерів',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('url', models.URLField(blank=True, verbose_name='Сайт')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('address_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Сервісний центр',
                'verbose_name_plural': 'Сервісні центри',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_saturday',
            field=models.CharField(blank=True, default='10:00 – 16:00', max_length=50, verbose_name='Робочі години (Сб)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_sunday',
            field=models.CharField(blank=True, default='вихідний', max_length=50, verbose_name='Неділя'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_sunday_en',
            field=models.CharField(blank=True, default='вихідний', max_length=50, null=True, verbose_name='Неділя'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_sunday_uk',
            field=models.CharField(blank=True, default='вихідний', max_length=50, null=True, verbose_name='Неділя'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_weekdays',
            field=models.CharField(blank=True, default='09:00 – 18:00', max_length=50, verbose_name='Робочі години (Пн–Пт)'),
        ),
    ]
