# Generated by Django 5.1.4 on 2026-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_update_map_embed_europe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_code',
            field=models.TextField(blank=True, default='<iframe src="https://maps.google.com/maps?q=Kyiv,+Ukraine&z=4&output=embed" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe>', help_text='Вставте повний код &lt;iframe&gt;...&lt;/iframe&gt;, отриманий у Google Maps через «Поділитися → Вставити карту». Якщо поле порожнє — показується карта Європи за замовчуванням.', verbose_name='Код карти (iframe з Google Maps або OpenStreetMap)'),
        ),
    ]
